{{- $bootstrap := .Values.bootstrap | int -}}


{{- range $i := until $bootstrap  }}
---
apiVersion: v1
kind: Service
metadata:
  name: nomad-server-{{ $i }}
  labels:
    name: nomad-server-{{ $i }}
spec:
  ports:
  - name: http
    port: 4646
    protocol: 'TCP'
  - name: rpc
    port: 4647
    protocol: 'TCP'
  - name: serf-tcp
    port: 4648
    protocol: 'TCP'
  selector:
    app: nomad-server-{{ $i }}
{{- end }}