{{- $replicas := .Values.bootstrap | int -}}

----
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nomad-server

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nomad-server
spec:
  selector:
    matchLabels:
      app: nomad-server
  replicas: {{ $replicas  }}
  serviceName: nomad-server-http
  template:
    metadata:
      labels:
        app: nomad-server
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
    spec:
      serviceAccountName: nomad-server
      terminationGracePeriodSeconds: 10
      containers:
      - name: nomad
        image: hashicorp/nomad:1.7.0-beta.2
        args:
        - "agent"
        - "-config=/etc/nomad-server/config/nomad.hcl"
        - "-dc={{ .Values.datacenter }}"
        - "-region={{ .Values.region }}"
        - "-bind=$(POD_IP)"
        - "-bootstrap-expect={{ .Values.bootstrap }}"
        - "-retry-max=5"
        - "-retry-interval=10s"
        env:
        - name: NOMAD_SKIP_DOCKER_IMAGE_WARN
          value: 'true'
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: http
          containerPort: 4646
          protocol: 'TCP'
        - name: rpc
          containerPort: 4647
          protocol: 'TCP'
        - name: serf-tcp
          containerPort: 4648
          protocol: 'TCP'
        - name: serf-udp
          containerPort: 4648
          protocol: 'UDP'
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: '1'
            memory: 512Mi
        volumeMounts:
        - name: nomad-server-config
          mountPath: /etc/nomad-server/config
          readOnly: true
        - name: nomad-server-certs
          mountPath: /etc/nomad-server/certs
          readOnly: true
        - name: data
          mountPath: /var/nomad-server/data
      volumes:
      - name: nomad-server-config
        configMap:
          name: nomad-server-config
      - name: nomad-server-certs
        secret:
          secretName: nomad-server-certs
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ['ReadWriteOnce']
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
