---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-docker-localhost-server
spec:
  secretName: vault-docker-localhost-server
  usages:
    - server auth
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'vault.docker.localhost'
  - 'vault-server'
  - 'vault-server.vault-system'
  - 'vault-server.vault-system.svc'
  - 'vault-server.vault-system.svc.cluster.local'
  - '*.vault-server'
  - '*.vault-server.vault-system'
  - '*.vault-server.vault-system.svc'
  - '*.vault-server.vault-system.svc.cluster.local'
  - 'localhost'
  ipAddresses:
  - '127.0.0.1'

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-docker-localhost-client
spec:
  secretName: vault-docker-localhost-client
  usages:
    - client auth
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'vault.docker.localhost'
  - 'vault-server'
  - 'vault-server.vault-system'
  - 'vault-server.vault-system.svc'
  - 'vault-server.vault-system.svc.cluster.local'
  - '*.vault-server'
  - '*.vault-server.vault-system'
  - '*.vault-server.vault-system.svc'
  - '*.vault-server.vault-system.svc.cluster.local'
  - 'localhost'
  ipAddresses:
  - '127.0.0.1'
