---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-server-config
data:
  vault.hcl: |
    cluster_name = "{{ .Values.datacenter }}"
    ui = true
    cluster_addr = "https://127.0.0.1:8201"
    api_addr = "https://127.0.0.1:8200"
    listener "tcp" {
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      tls_client_ca_file = "/etc/vault/tls/car.crt"
      tls_cert_file = "/etc/vault/tls/tls.crt"
      tls_key_file  = "/etc/vault/tls/tls.key"
    }
    cache {
      use_auto_auth_token = false
    }
    storage "raft" {
      path = "/var/lib/vault/data"
    }
    disable_cache = true
    disable_mlock = true
