---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: vault-server-transport
spec:
  serverName: vault.docker.localhost

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: vault-server-route
spec:
  entryPoints:
  - websecure
  routes:
  - match: 'Host(`vault.docker.localhost`)'
    kind: Rule
    services:
    - kind: Service
      name: vault-server
      namespace: vault-system
      scheme: https
      passHostHeader: true
      serversTransport: vault.docker.localhost
      port: 8200
  tls:
    secretName: vault.docker.localhost
