apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-server
spec:
  serviceName: vault-server
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: vault-server
  template:
    metadata:
      labels:
        app: vault-server
    spec:
      serviceAccountName: vault-server
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - vault-server
            topologyKey: kubernetes.io/hostname
      containers:
      - name: vault-server
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        args:
        - 'server'
        - '-config=/etc/vault/vault.d/vault.hcl'
        env:
        - name: VAULT_RAFT_NODE_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: api
          containerPort: 8200
          protocol: 'TCP'
        - name: cluster
          containerPort: 8201
          protocol: 'TCP'
        resources:
          requests:
            cpu: '250m'
            memory: '256Mi'
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        volumeMounts:
        - name: vault-server-config
          mountPath: /etc/vault/vault.d
        - name: vault-server-data
          mountPath: /var/lib/vault
        - name: vault-server-tls
          mountPath: /etc/vault/tls
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      volumes:
      - name: vault-server-config
        configMap:
          name: vault-server-config
      - name: vault-server-tls
        secret:
          secretName: vault-docker-localhost-server
  volumeClaimTemplates:
  - metadata:
      name: vault-server-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
