---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jobs.nomad.asytech.com
spec:
  group: nomad.asytech.com
  names:
    kind: Job
    plural: jobs
    singular: job
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              jobHCL:
                type: string
                description: HashiCorp Configuration Language (HCL) code for the Nomad job
