---
apiVersion: v1
kind: Namespace
metadata:
  name: datacenter-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: datacenter-system
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: All applications for datacenter
  sourceRepos:
  - '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: cert-manager
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: kube-system
    server: https://kubernetes.default.svc
    name: in-cluster

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: datacenter-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: 1.13.2
    helm:
      values: |-
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
