---
apiVersion: v1
kind: Namespace
metadata:
  name: consul-system

---
apiVersion: v1
kind: Namespace
metadata:
  name: nomad-system
  
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hashistack-system
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: consul-system
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: nomad-system
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: kube-system
    server: https://kubernetes.default.svc
    name: in-cluster

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul-server
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: hashistack-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: consul
    targetRevision: 1.3.0
    helm:
      values: |-
        global:
          enabled: true
          logJSON: true
          datacenter: development
          gossipEncryption:
            autoGenerate: true
          argocd:
            enabled: true
          tls:
            enabled: true
            enableAutoEncrypt: true
          acls:
            manageSystemACLs: true
          metrics:
            enabled: true
            enableAgentMetrics: true
            enableGatewayMetrics: true
            enableTelemetryCollector: true
        terminatingGateways:
          enabled: false
        meshGateway:
          enabled: false
        ui:
          enabled: true
          metrics:
            enabled: true
        syncCatalog:
          enabled: true
          default: false
          toConsul: true
          toK8S: false
          k8sAllowNamespaces: ['victoriametrics-system']
          extraLabels:
            vector-logs/enabled: 'true'
            vector-logs/name: 'consul-sync-catalog'
        connectInject:
          enabled: true
          extraLabels:
            vector-logs/enabled: 'true'
            vector-logs/name: 'consul-connect-inject'
          metrics:
            defaultEnableMerging: true
        server:
          replicas: 2
          bootstrapExpect: 2
          connect: true
          exposeGossipAndRPCPorts: false
          exposeService:
            enabled: false
          extraConfig: |
            {"log_json": true, "log_level": "info"}
          extraLabels:
            vector-logs/enabled: 'true'
            vector-logs/name: 'consul-server'
        client:
          enabled: true
          affinity: |
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/master
                    operator: DoesNotExist
  destination:
    server: https://kubernetes.default.svc
    namespace: consul-system

---
apiVersion: traefik.containo.us/v1alpha1
kind: ServersTransport
metadata:
  name: consul
  namespace: consul-system
spec:
  insecureSkipVerify: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: consul-route
  namespace: kube-system
spec:
  entryPoints:
  - websecure
  routes:
  - match: 'Host(`consul.docker.localhost`)'
    kind: Rule
    services:
    - kind: Service
      name: consul-server-consul-ui
      namespace: consul-system
      scheme: https
      serversTransport: consul
      port: 443
