---
apiVersion: v1
kind: Namespace
metadata:
  name: nomad-system

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nomad-system
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  description: Setup nomad servers
  sourceRepos:
  - '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: nomad-system
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: kube-system
    server: https://kubernetes.default.svc
    name: in-cluster

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nomad-servers
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: nomad-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://github.com/gperreymond/argocd-nomad.git
    path: charts/nomad-servers-0.1.0
    targetRevision: master
    helm:
      releaseName: nomad-servers
      valueFiles:
        - values.yaml
      values: |
        region: europe
        datacenter: development
  destination:
    server: https://kubernetes.default.svc
    namespace: nomad-system