---
apiVersion: v1
kind: Namespace
metadata:
  name: consul-system

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hashistack-system
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
  - '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: consul-system
    server: https://kubernetes.default.svc
    name: in-cluster
  - namespace: kube-system
    server: https://kubernetes.default.svc
    name: in-cluster

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consul-server
  namespace: argocd-system
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: hashistack-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: consul
    targetRevision: 1.3.0
    helm:
      values: |-
        global:
          enabled: true
          logJSON: true
          datacenter: development
          gossipEncryption:
            autoGenerate: true
          argocd:
            enabled: true
          tls:
            enabled: true
            enableAutoEncrypt: true
          acls:
            manageSystemACLs: true
          metrics:
            enabled: true
            enableAgentMetrics: true
            enableTelemetryCollector: true
        terminatingGateways:
          enabled: true
        meshGateway:
          enabled: true
        ui:
          enabled: true
          metrics:
            enabled: true
        syncCatalog:
          enabled: true
          default: false
          toConsul: true
          toK8S: false
          extraLabels:
            vector-logs/enabled: 'true'
            vector-logs/name: 'consul-sync-catalog'
        server:
          replicas: 1
          bootstrapExpect: 1
          connect: true
          extraConfig: |
            {"log_json": true, "log_level": "info"}
          extraLabels:
            vector-logs/enabled: 'true'
            vector-logs/name: 'consul-server'
        client:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: consul-system
