---
apiVersion: v1
kind: Namespace
metadata:
  name: tenant-name

---
apiVersion: v1
kind: Namespace
metadata:
  name: nomad-system

---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nomad-server
  namespace: nomad-system
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: nomad-server
  template:
    metadata:
      labels:
        app: nomad-server
    spec:
      containers:
      - name: nomad
        image: hashicorp/nomad:1.6.3
        args: ['agent', '-dev']
        ports:
        - name: http
          containerPort: 4646
          protocol: 'TCP'
        - name: rpc
          containerPort: 4647
          protocol: 'TCP'
        - name: serf-tcp
          containerPort: 4648
          protocol: 'TCP'
        - name: serf-udp
          containerPort: 4648
          protocol: 'UDP'
        resources:
          requests:
            cpu: 100m
            memory: 64Mo
          limits:
            cpu: '1'
            memory: 512Mo

---
apiVersion: v1
kind: Service
metadata:
  name: nomad-server
  namespace: nomad-system
  labels:
    name: nomad-server
spec:
  ports:
    - name: http
      port: 4646
      protocol: 'TCP'
    - name: rpc
      port: 4647
      protocol: 'TCP'
  selector:
    app: nomad-server

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-nomad
  namespace: argocd-system
spec:
  project: default
  source:
    repoURL: https://github.com/gperreymond/argocd-nomad.git
    targetRevision: master
    path: charts/argocd-nomad
  destination:
    server: https://kubernetes.default.svc
    namespace: tenant-name