apiVersion: batch/v1
kind: Job
metadata:
  name: nomad-certs-init
  annotations:
    'helm.sh/hook': 'pre-install,pre-upgrade'
    'helm.sh/hook-weight': '-10'
    'helm.sh/hook-delete-policy': hook-succeeded
spec:
  template:
    metadata:
      name: nomad-certs-init
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: 'alpine:3.3'
        command:
        - '/bin/sleep'
        - '10'