apiVersion: v1
kind: Service
metadata:
  name: nomad
  labels:
    name: nomad
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 4646
      protocol: TCP
    - name: rpc
      port: 4647
      protocol: TCP
  selector:
    app: nomad