apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nomad
spec:
  serviceName: nomad
  replicas: {{ .Values.bootstrap_expect }}
  selector:
    matchLabels:
      app: nomad
  template:
    metadata:
      labels:
        app: nomad
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nomad
            topologyKey: kubernetes.io/hostname
      containers:
      - name: nomad
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        args:
        - 'agent'
        {{- range .Values.bootstrap_expect }}
        - '-retry-join=nomad-{{ . }}.nomad.$(NAMESPACE).svc.cluster.local'
        {{- end }}
        - '-config=/etc/nomad/nomad.d/server.hcl'
        - '-encrypt=$(GOSSIP_ENCRYPTION_KEY)'
        env:
        - name: GOSSIP_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: nomad-encryption-key
              key: data
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 4646
          protocol: 'TCP'
        - name: rpc
          containerPort: 4647
          protocol: 'TCP'
        - name: serf-tcp
          containerPort: 4648
          protocol: 'TCP'
        - name: serf-udp
          containerPort: 4648
          protocol: 'UDP'
        resources:
          requests:
            cpu: '500m'
            memory: '1Gi'
        volumeMounts:
        - name: nomad-config
          mountPath: /etc/nomad/nomad.d
        - name: nomad-data
          mountPath: /var/lib/nomad
        - name: nomad-tls
          mountPath: /etc/nomad/tls
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      volumes:
      - name: nomad-config
        configMap:
          name: nomad-config
      - name: nomad-tls
        secret:
          secretName: nomad-tls-certs
  volumeClaimTemplates:
  - metadata:
      name: nomad-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
