---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nomad-server-config
data:
  server.hcl: |
    data_dir = "/var/lib/nomad"

    acl {
      enabled = true
    }

    consul {
      ssl = true
      server_service_name = "nomad"
      client_service_name = "nomad-client"
      auto_advertise = true
      server_auto_join = true
      client_auto_join = true
    }

    log_level = "INFO"
    log_json = true

    leave_on_terminate = true
    leave_on_interrupt = true

    telemetry {
      collection_interval = "1s"
      disable_hostname = true
      prometheus_metrics = true
      publish_allocation_metrics = true
      publish_node_metrics = true
    }

    region = "{{ .Values.region }}"
    datacenter = "{{ .Values.datacenter }}"
    
    server {
      enabled = true
      bootstrap_expect = {{ .Values.bootstrap_expect }}
      rejoin_after_leave = true
    }

    client {
      enabled = false
    }

    ui {
      enabled =  true
    }

    tls {
      http = true
      rpc = true
      verify_server_hostname = true
      verify_https_client = false  # TODO: need to be true
      ca_file = "/etc/nomad/tls/nomad-agent-ca.pem"
      cert_file = "/etc/nomad/tls/global-server-nomad.pem"
      key_file = "/etc/nomad/tls/global-server-nomad-key.pem"
    }

    bind_addr = "0.0.0.0"
