---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nomad-server

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nomad-server
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nomad-server
subjects:
- kind: ServiceAccount
  name: nomad-server
roleRef:
  kind: Role
  name: nomad-server
  apiGroup: rbac.authorization.k8s.io
