---
apiVersion: v1
kind: Service
metadata:
  name: nomad-server
  labels:
    name: nomad-server
spec:
  ports:
    - name: http
      port: 4646
      protocol: TCP
    - name: rpc
      port: 4647
      protocol: TCP
    - name: serf-tcp
      port: 4648
      protocol: TCP
    - name: serf-udp
      port: 4648
      protocol: UDP
  selector:
    app: nomad-server
