apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nomad-server
spec:
  serviceName: nomad-server
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: nomad-server
  template:
    metadata:
      labels:
        app: nomad-server
    spec:
      serviceAccountName: nomad-server
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - nomad-server
            topologyKey: kubernetes.io/hostname
      initContainers:
      - name: consul-login
        image: 'hashicorp/consul:1.17.0'
        command: ['/bin/sh', '-c']
        args:
        - |
          consul login -method 'consul-server-consul-k8s-component-auth-method' \
            -bearer-token-file '/run/secrets/kubernetes.io/serviceaccount/token' \
            -token-sink-file 'consul.token' \
            -http-addr=https://localhost:8501
          cat consul.token
      containers:
      - name: nomad-server
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        args:
        - 'agent'
        - '-config=/etc/nomad/nomad.d/server.hcl'
        - '-encrypt=$(GOSSIP_ENCRYPTION_KEY)'
        env:
        - name: NOMAD_SKIP_DOCKER_IMAGE_WARN
          value: 'true'
        - name: GOSSIP_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: nomad-server-gossip-encryption-key
              key: data
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 4646
          protocol: 'TCP'
        - name: rpc
          containerPort: 4647
          protocol: 'TCP'
        - name: serf-tcp
          containerPort: 4648
          protocol: 'TCP'
        - name: serf-udp
          containerPort: 4648
          protocol: 'UDP'
        resources:
          requests:
            cpu: '250m'
            memory: '256Mi'
        volumeMounts:
        - name: nomad-server-config
          mountPath: /etc/nomad/nomad.d
        - name: nomad-server-data
          mountPath: /var/lib/nomad
        - name: nomad-server-tls
          mountPath: /etc/nomad/tls
      - name: consul-client
        image: 'hashicorp/consul:1.17.0'
        args:
        - 'agent'
        - '-config-file=/etc/consul/consul.d/client.hcl'
        - '-encrypt=$(GOSSIP_ENCRYPTION_KEY)'
        env:
        - name: GOSSIP_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: consul-server-consul-gossip-encryption-key
              key: key
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - consul leave
        ports:
        - name: 'http'
          containerPort: 8501
          protocol: 'TCP'
        - name: 'serf-lan-tcp'
          containerPort: 8301
          protocol: 'TCP'
        - name: 'serf-lan-udp'
          containerPort: 8301
          protocol: 'UDP'
        - name: 'serf-wan-tcp'
          containerPort: 8302
          protocol: 'TCP'
        - name: 'serf-wan-udp'
          containerPort: 8302
          protocol: 'UDP'
        - name: 'server-rpc'
          containerPort: 8300
          protocol: 'TCP'
        - name: 'grpc'
          containerPort: 8502
          protocol: 'TCP'
        resources:
          requests:
            cpu: '250m'
            memory: '256Mi'
        volumeMounts:
        - name: consul-client-config
          mountPath: /etc/consul/consul.d
        - name: consul-client-data
          mountPath: /var/lib/consul
        - name: consul-client-tls
          mountPath: /etc/consul/tls
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      volumes:
      - name: nomad-server-config
        configMap:
          name: nomad-server-config
      - name: nomad-server-tls
        secret:
          secretName: nomad-server-tls-certs
      - name: consul-client-config
        configMap:
          name: consul-client-config
      - name: consul-client-tls
        secret:
          secretName: consul-server-consul-ca-cert
  volumeClaimTemplates:
  - metadata:
      name: nomad-server-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
  - metadata:
      name: consul-client-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
