apiVersion: v1
kind: ConfigMap
metadata:
  name: whoami-config
data:
  job.hcl: |
    job "whoami" {
      datacenters = ["{{ .Values.datacenter }}"]
      type        = "service"
      group "web" {
        count = 1
        network {
          port "http" {
            to = 80
          }
        }
        service {
          provider = "nomad"
          name = "whoami-http"
          port = "http"
        }
        task "whoami" {
          driver = "docker"
          config {
            image = "traefik/whoami:v1.10"
            ports = ["http"]
          }
          resources {
            cpu    = {{ .Values.resources.cpu }}
            memory = {{ .Values.resources.memory }}
            memory_max = {{ .Values.resources.memory_max }}
          }
        }
      }
    }