{{- $name = .Values.name -}}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}-config
data:
  job.hcl: |
    job "{{ $name }}" {
      datacenters = ["{{ .Values.datacenter }}"]
      type        = "service"
      group "{{ $name }}" {
        count = 1
        network {
          {{- range .Values.services }}
          {{- if eq .provider "nomad" }}
          port "{{ .name }}" {
            to = {{ .port }}
          }
          {{- end }}
          {{- end }}
        }
        {{- range .Values.services }}
        {{- if eq .provider "nomad" }}
        service {
          provider = "{{ .provider }}"
          name = "{{ $name }}-{{ .name }}"
          port = "{{ .name }}"
        }
        {{- end }}
        {{- end }}
        task "{{ $name }}" {
          driver = "docker"
          config {
            image = "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            ports = ["http"]
          }
          resources {
            cpu    = {{ .Values.resources.cpu }}
            memory = {{ .Values.resources.memory }}
            memory_max = {{ .Values.resources.memory_max }}
          }
        }
      }
    }