apiVersion: v1
kind: ConfigMap
metadata:
  name: whoami-config
data:
  job.hcl: |
    job "whoami" {
      datacenters = ["dc1"]
      type        = "service"
      group "web" {
        count = 1
        network {
          port "http" {
            to = 80
          }
        }
        task "whoami" {
          driver = "docker"
          config {
            image = "traefik/whoami:v1.10"
            ports = ["http"]
          }
          resources {
            cpu    = 500
            memory = 256
          }
          service {
            name = "whoami-http"
            port = "http"
          }
        }
      }
    }