apiVersion: batch/v1
kind: Job
metadata:
  name: nomad-job-apply
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: nomad
        image: hashicorp/nomad:1.6.3
        imagePullPolicy: Always
        env:
        - name: NOMAD_ADDR
          value: http://192.168.1.35:4646
        args:
        - job
        - run
        - /etc/whoami/job.hcl
        volumeMounts:
        - name: whoami-config-volume
          mountPath: /etc/whoami
      restartPolicy: Never
      volumes:
      - name: whoami-config-volume
        configMap:
          name: whoami-config
  backoffLimit: 1