apiVersion: nomad.asytech.com/v1
kind: NomadJob
metadata:
  labels:
    app.kubernetes.io/name: nomadjob
    app.kubernetes.io/instance: nomadjob-sample
    app.kubernetes.io/part-of: src
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: src
  name: nomadjob-sample
spec:
  # TODO(user): Add fields here
