---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-nomad-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nomad-server-cert
spec:
  secretName: nomad-server-tls
  duration: 2160h0m0s # 90 days
  renewBefore: 360h0m0s # 15 days
  commonName: nomad-server
  isCA: true
  privateKey:
    size: 2048
    algorithm: RSA
  issuerRef:
    name: selfsigned-nomad-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - server auth

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nomad-client-cert
spec:
  secretName: nomad-client-tls
  duration: 2160h0m0s # 90 days
  renewBefore: 360h0m0s # 15 days
  commonName: nomad-client
  isCA: true
  privateKey:
    size: 2048
    algorithm: RSA
  issuerRef:
    name: selfsigned-nomad-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - client auth

# ---
# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: nomad-server
#   namespace: nomad-system
# spec:
#   selector:
#     matchLabels:
#       app: nomad-server
#   serviceName: nomad-server
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         app: nomad-server
#     spec:
#       terminationGracePeriodSeconds: 10
#       containers:
#       - name: nomad
#         image: hashicorp/nomad:1.6.3
#         args: ['agent', '-config', '/nomad/config.hcl']
#         ports:
#         - name: http
#           containerPort: 4646
#           protocol: 'TCP'
#         - name: rpc
#           containerPort: 4647
#           protocol: 'TCP'
#         - name: serf-tcp
#           containerPort: 4648
#           protocol: 'TCP'
#         - name: serf-udp
#           containerPort: 4648
#           protocol: 'UDP'
#         resources:
#           requests:
#             cpu: 100m
#             memory: 64Mi
#           limits:
#             cpu: '1'
#             memory: 512Mi
#         volumeMounts:
#         - name: config-volume
#           mountPath: /etc/nomad-server
#         - name: nomad-data
#           mountPath: /var/nomad/data
#   volumes:
#   - name: config-volume
#     configMap:
#       name: nomad-server-config
#   volumeClaimTemplates:
#   - metadata:
#       name: nomad-data
#     spec:
#       accessModes: ['ReadWriteOnce']
#       storageClassName: standard
#       resources:
#         requests:
#           storage: 5Gi

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nomad-server
#   namespace: nomad-system
#   labels:
#     name: nomad-server
# spec:
#   ports:
#   - name: http
#     port: 4646
#     protocol: 'TCP'
#   - name: rpc
#     port: 4647
#     protocol: 'TCP'
#   selector:
#     app: nomad-server
