---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-nomad-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nomad-server-certs
spec:
  secretName: nomad-server-certs
  duration: 2160h0m0s # 90 days
  renewBefore: 360h0m0s # 15 days
  commonName: server.{{ .Values.region }}.nomad
  dnsNames:
  - 'server.{{ .Values.region }}.nomad'
  isCA: true
  privateKey:
    size: 2048
    algorithm: RSA
  issuerRef:
    name: selfsigned-nomad-issuer
    kind: ClusterIssuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nomad-client-certs
spec:
  secretName: nomad-client-certs
  duration: 2160h0m0s # 90 days
  renewBefore: 360h0m0s # 15 days
  commonName: client.{{ .Values.region }}.nomad
  dnsNames:
  - 'client.{{ .Values.region }}.nomad'
  isCA: true
  privateKey:
    size: 2048
    algorithm: RSA
  issuerRef:
    name: selfsigned-nomad-issuer
    kind: ClusterIssuer
    group: cert-manager.io
