---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-nomad-issuer
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nomad-server-cert
spec:
  secretName: nomad-server-tls
  duration: 2160h0m0s # 90 days
  renewBefore: 360h0m0s # 15 days
  commonName: nomad-server
  isCA: true
  privateKey:
    size: 2048
    algorithm: RSA
  issuerRef:
    name: selfsigned-nomad-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - server auth

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nomad-client-cert
spec:
  secretName: nomad-client-tls
  duration: 2160h0m0s # 90 days
  renewBefore: 360h0m0s # 15 days
  commonName: nomad-client
  isCA: true
  privateKey:
    size: 2048
    algorithm: RSA
  issuerRef:
    name: selfsigned-nomad-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  usages:
    - client auth
