---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nomad.asytech.com
  resources:
  - nomadjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nomad.asytech.com
  resources:
  - nomadjobs/finalizers
  verbs:
  - update
- apiGroups:
  - nomad.asytech.com
  resources:
  - nomadjobs/status
  verbs:
  - get
  - patch
  - update
